### ISSUE TITLE
날짜가 지나면 intake, burned, resultcalorie가 0으로 초기화되어 DB에 삽입이 되지 않는 오류

### ISSUE THREAD

**Issue by sinsohi** [sinsohi/Ottogi_Family#108]
## 어떤 버그인가요?

날짜가 지나면 intake, burned, resultcalorie가 0으로 초기화되어 DB에 삽입이 되지 않는 오류

## 어떤 상황에서 발생한 버그인가요?
![image](https://github.com/sinsohi/Ottogi_Family/assets/136775478/e77c4b5e-0b31-4358-a4e4-511e9ee7fd5e)
날짜가 지나고 접속을 하면, DB에 0으로 초기화된 값이 삽입이 된다고 하셨는데,
DB에 초기화된 데이터가 삽입이 되지 않아, 사진처럼 undifined, Nan kcal로 뜨게 됩니다.

오류를 수정해주시면 감사하겠습니다.

**Comment by KimYeYoung125** [comment]
dailyrecord 페이지에 접속했을 때 진행되는 방식이라 그런듯합니다. 빠르게 수정하겠습니다!

**Comment by sinsohi** [comment]
넵 감사합니다!

**Comment by sinsohi** [comment]
제가 오류 해결했습니다~
