### ISSUE TITLE
템플릿 엔진 ejs 이유

### ISSUE THREAD

**Issue by CoCo-1223** [sinsohi/Ottogi_Family#15]
Calender html 안에 DB데이터를 꽂아줘야합니다.
html안에 데이터를 꽂아넣는 템플릿 엔진이 필요할 것 같습니다.
템플릿 엔진으로 ejs를 사용하면 어떨까요?

@sinsohi @starsaverKDH

**Comment by sinsohi** [comment]
좋습니다!
ejs 템플릿 엔진은 새로운 문법 익힐 필요없이 자바스크립트 문법을 그대로 사용할 수 있어서 적절한 것 같습니다.
제가 ejs 템플릿 엔진 셋팅을 맡아서 해도 괜찮을까요?

**Comment by CoCo-1223** [comment]
좋아요! 부탁합니다

**Comment by sinsohi** [comment]
ejs 템플릿 엔진 셋팅 완료 했습니다.
ejs 파일은 아래의 사진처럼 반드시 views 폴더 아래에 만들어야 합니다.
@CoCo-1223  @starsaverKDH 

![image](https://github.com/sinsohi/Ottogi_Family/assets/136775478/e3d2ad99-6944-4ca2-9e63-feb7da81661b)

**Comment by starsaverKDH** [comment]
좋습니다 확인완료했어요!
