### ISSUE TITLE
BMI 계산 수식

### ISSUE THREAD

**Issue by KimYeYoung125** [sinsohi/Ottogi_Family#30]
BMI 계산을 데일리 레코드 페이지에서 하기로 말씀드렸으나, 키&몸무게를 입력하고 변경 가능한 세팅 페이지에서 함이 깔끔할 듯 싶습니다.

**Comment by sinsohi** [comment]
넵 좋습니다.

예영님 궁금한 게 있습니다.

저희가 회의한 바로는 BMI를 계산하여 6가지의 결과로 분류하기로 했는데, DB에 어떤 key와 value로 넣을 생각이신가요?

BMI는 user_info 컬렉션에 넣으시는 건가요??

**Comment by KimYeYoung125** [comment]
key는 사용자의 ID로 하겠습니다. 또, 세팅 페이지에서 유저에게 받아오는 정보를 정리하기 위해 user_settinginfo 컬렉션을 따로 만들었으나, BMI를 포함한 모든 정보를 user_info에 넣는 것이 개발에 편리할 것 같습니다. 어떻게 생각하시나요? 동의하신다면 그렇게 변경하겠습니다.

**Comment by CoCo-1223** [comment]
좋은거같아요!!!!

**Comment by sinsohi** [comment]
훨씬 깔끔한 것 같아요! 좋습니다
