### ISSUE TITLE
헬뚝이 구현 방향에 대하여

### ISSUE THREAD

**Issue by sinsohi** [sinsohi/Ottogi_Family#35]
기존에는 gltf loader를 이용해서 glb로 export한 3D 헬뚝이 모델을 three.js에서 mesh로 사용하는 방향으로 개발을 진행하려고 했습니다.
이 경우, mesh에서 Animation Mixer를 뽑아서 clipAction을 통해 애니메이션 배열에서 각각의 clip을 꺼내올 수 있고, clip을 play하여 흔들거리는 애니메이션을 재생할 수 있습니다.

하지만 기존의 방식은 너무 많은 glb 파일을 만들어야 한다는 단점이 있습니다.

bmi, 수면시간이 갱신될 때마다 헬뚝이의 허리 둘레, 흔들거림의 속도, 다크써클 단계가 업데이트 되어야 한다는 점을 고려했을 때 기존의 구현 계획이 적절하지 않다고 판단을 했습니다.

그래서 three.js 로 직접 눈, 머리, 다크써클, 몸통의 mesh를 만들고 그룹화하여 구현하고자 합니다. 
대신 디자인 측면에서 blender로 디자인한 헬뚝이 mesh보다 퀄리티가 떨어질 수도 있습니다.. 

다들 어떻게 생각하시나요?

**Comment by CoCo-1223** [comment]
음..그러네요 디자인수정할때 각각 glb파일을 모두 바꾸는건 너무 비효율일 것 같아여 디자인측면에서 약간 떨어지더라도 장기적인 프로젝트 관점에서 저도 2번째방식이 더 나은거같아요
