### ISSUE TITLE
데이터베이스 컬렉션

### ISSUE THREAD

**Issue by KimYeYoung125** [sinsohi/Ottogi_Family#36]
setting 페이지에서 입력 받는 정보는 가장 최근 저장된 정보만 유의미하므로 user_settinginfo는 삭제하고 user_info에 모두 포함 시켰습니다. dailyrecord의 식단(아침, 점심, 저녁), 운동, 수면 시간은 각각 컬렉션을 나누어 효율적인 개발에 힘쓰겠습니다. 참조해주시면 감사하겠습니다. 더 좋은 의견이 있다면 편하게 말씀 주세요.

**Comment by sinsohi** [comment]
넵 좋아요
예영님이 말씀하신 대로 db 컬렉션을 나누면 보기에도 깔끔하고, 데이터를 불러올 땐 id로 불러오면 될 것 같네요!
