### ISSUE TITLE
DB에 포함되는 사용자 정보

### ISSUE THREAD

**Issue by KimYeYoung125** [sinsohi/Ottogi_Family#38]
제가 만든 user_info, 데일리 레코드 정보 컬렉션을 보시면 모두 사용자의 ID(userNickname)가 포함되어 있습니다. 여러분들이 개발 중 ID 만으로는 사용자 식별이 어렵다고 판단 되신다면 password, username도 추가하려고 합니다. 언제든지 말씀해주세요!

**Comment by sinsohi** [comment]
향후 회원 가입 페이지에서 닉네임 중복 확인 기능을 추가할 예정입니다. 
그래서 userNickname을 통해 데이터를 불러와서 개발을 진행해도 될 것 같습니다. 
만약 username 도 데일리 레코드 정보 컬렉션에 넣어야 한다고 생각이 들면, 추가로 예영님께 말씀 드리겠습니다!

**Comment by KimYeYoung125** [comment]
확인해주셔서 감사합니다
