### ISSUE TITLE
DB 컬렉션명

### ISSUE THREAD

**Issue by KimYeYoung125** [sinsohi/Ottogi_Family#39]
dailyrecord 페이지에서 입력 받는 정보는 크게 총 세가지 입니다. 식단, 운동량, 수면 시간이지요. 식단은 breakfast, lunch, dinner 이렇게 세 개의 컬렉션으로 나누었고 운동량과 수면 시간은 각각 DRexercise와 DRsleeptime로 명명하겠습니다. 개발에 착오 없으시길 바랍니다.

**Comment by sinsohi** [comment]
네 확인했습니다

**Comment by CoCo-1223** [comment]
그  혹시 #43 이 이슈 보시고 날짜도 추가해주실 수 있나요?

**Comment by KimYeYoung125** [comment]
네 날짜도 추가해 작업하겠습니다!
