### ISSUE TITLE
Three.js 설치 및 헬뚝이 생성

### ISSUE THREAD

**Issue by sinsohi** [sinsohi/Ottogi_Family#4]
## 어떤 기능인가요?

가족들의 건강 상태를 반영할 헬뚝이 생성
 (BMI에 따라 size 변경하는 기능은 추후에 개발 예정)

Three.js 라이브러리를 이용하여 메인페이지에 3D 헬뚝이 1개 생성

## 작업 상세 내용

- [x] Three.js 설치 및 셋팅
- [x] blender를 이용하여 헬뚝이 커스텀
- [x] blender에서 헬뚝이 mesh를 glb 파일로 내보내기
- [x] 커스텀한 헬뚝이 메인페이지에 나타나도록 구현

**Comment by sinsohi** [comment]
![헬뚝이](https://github.com/sinsohi/Ottogi_Family/assets/136775478/d307fcf8-5bb0-47ab-9836-71053f431077)

blender를 이용해 커스텀한 헬뚝이입니다.

**Comment by CoCo-1223** [comment]
잘 만드셨네요!!
