### ISSUE TITLE
Feature_calender 날짜별 기능 

### ISSUE THREAD

**Issue by CoCo-1223** [sinsohi/Ottogi_Family#43]
닉네임과 날짜 별로 데이터를 불러오는 기능을 구현 하려고하는데 
그러려면 날짜별 기록이 필요해 데일리 리코드페이지에서 건강기록 저장할 때 날짜도 같이 저장되도록 연동 해주시면 좋겠습니다. 
@KimYeYoung125
ex. 
date : 2022-04-15
date : 0000-00-00
이런 식으로 몽고 디비에 넣어주세요!!

**Comment by CoCo-1223** [comment]
일단 제가 미리 몽고DB에 샘플 만들어둘게요

**Comment by KimYeYoung125** [comment]
확인했습니다 바로 작업 시작하겠습니다!!
