### ISSUE TITLE
가족 추가 기능 

### ISSUE THREAD

**Issue by CoCo-1223** [sinsohi/Ottogi_Family#63]
> 가족 추가 기능 개발 계획

## 작업 상세 내용

기존의 아이디로 추가하려고 했던 계획은 편의성 측면에서 조금 떨어져서 유저의 닉네임으로 추가하는 기능으로 개발을 진행해보려고 합니다 (유저의 닉네임은 중복이 불가능하여 중복 될 리는 없음)

**Comment by sinsohi** [comment]
좋습니다!
저도 빠른 시일 내에 닉네임 중복 여부 확인 기능을 구현하도록 하겠습니다

**Comment by KimYeYoung125** [comment]
알겠습니다!
