### ISSUE TITLE
DB에 임의로 RDA 데이터 삽입

### ISSUE THREAD

**Issue by sinsohi** [sinsohi/Ottogi_Family#78]
현재 로그인한 유저의 일일 권장 칼로리(RDA)를 불러오는 기능을 구현 중에 있습니다.
이를 위해 user_info 컬렉션에서 현재 로그인한 유저의 document에 RDA 데이터를 임의로 삽입할 예정입니다.

이는 기능 개발 및 테스트를 위한 것이니, 버그 수정 작업 중에 착오 없이 진행되기를 바랍니다.

추가적인 문의 사항이 있으시면 언제든 댓글로 말씀해주세요

**Comment by KimYeYoung125** [comment]
알겠습니다.
