### ISSUE TITLE
개발에 필요한 일일 섭취칼로리, 소모칼로리 계산에 대해

### ISSUE THREAD

**Issue by KimYeYoung125** [sinsohi/Ottogi_Family#81]
제 코드를 보시면 dailyrecord 화면에 표시하기 위해 따로 걸러둔 데이터가 있습니다.  ex) useres, userbf
이 변수들을 이용해 데이터에 있는 소모 칼로리를 모두 더한 후 userNickname, timestamp와 함께 user_info에 넣겠습니다.
변수 이름은 각각 intake, burned,  resultcalorie로 작업할 예정이니 혼동 없으시길 바랍니다!

**Comment by KimYeYoung125** [comment]
resultcalorie는 intake, burned 두 값의 차를 계산한 것입니다.

**Comment by CoCo-1223** [comment]
넹
