### ISSUE TITLE
develop branch 이슈

### ISSUE THREAD

**Issue by sinsohi** [sinsohi/Ottogi_Family#9]
기능 개발을 위한 브랜치들을 병합하기 위해 사용할 develop branch를 생성하는건 어떨까요?
모든 기능이 추가되고 버그가 수정되어 배포 가능한 안정적인 상태가 되면 main branch에 merge 하는거죠. 
평소에는 이 branch를 기반으로 개발을 진행하고요!

**Comment by CoCo-1223** [comment]
오 좋은 생각인거 같아요!!!

**Comment by starsaverKDH** [comment]
네 좋습니다!
